### ISSUE TITLE
The bounding box in CSV file does not seem correctly on the map

### ISSUE THREAD

**Issue by ghc20** [usgin/metadata-repository#39]

**Comment by smrgeoinfo** [comment]
For files uploaded from a CSV, if you look at the unpublished record in the editor, the bounding boxes are not correctly read from the imported metadata (which has correct lat/long bounding box). In order to validate and publish, you have to draw a bounding box in the map widget, then make sure the lat/long values are correct.  
Editor code has to correctly read and plot bounding boxes or csv imported records...

**Comment by ghc20** [comment]
Fixed in Commit 747bf95aac73e6d4fa72eacc2573614e8f451619
